// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public interface CreateFarmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.CreateFarmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   * @return The confirmation.
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   * @return The bytes for confirmation.
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
