// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public interface CreateProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.CreateProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @return A list containing the animalParts.
   */
  java.util.List<java.lang.Long> getAnimalPartsList();
  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @return The count of animalParts.
   */
  int getAnimalPartsCount();
  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @param index The index of the element to return.
   * @return The animalParts at the given index.
   */
  long getAnimalParts(int index);
}
