// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public interface GetAnimalIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.GetAnimalIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
