// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

/**
 * Protobuf type {@code com.example.testrestapi.GetTrayResponse}
 */
public final class GetTrayResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.testrestapi.GetTrayResponse)
    GetTrayResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTrayResponse.newBuilder() to construct.
  private GetTrayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTrayResponse() {
    description_ = "";
    animalParts_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTrayResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTrayResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            maxWeight_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animalParts_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            animalParts_.addLong(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              animalParts_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              animalParts_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animalParts_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.testrestapi.SlaughterHouse.internal_static_com_example_testrestapi_GetTrayResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.testrestapi.SlaughterHouse.internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.testrestapi.GetTrayResponse.class, com.example.testrestapi.GetTrayResponse.Builder.class);
  }

  public static final int MAXWEIGHT_FIELD_NUMBER = 1;
  private double maxWeight_;
  /**
   * <code>double maxWeight = 1;</code>
   * @return The maxWeight.
   */
  @java.lang.Override
  public double getMaxWeight() {
    return maxWeight_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANIMALPARTS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList animalParts_;
  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @return A list containing the animalParts.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getAnimalPartsList() {
    return animalParts_;
  }
  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @return The count of animalParts.
   */
  public int getAnimalPartsCount() {
    return animalParts_.size();
  }
  /**
   * <code>repeated int64 animalParts = 3;</code>
   * @param index The index of the element to return.
   * @return The animalParts at the given index.
   */
  public long getAnimalParts(int index) {
    return animalParts_.getLong(index);
  }
  private int animalPartsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (java.lang.Double.doubleToRawLongBits(maxWeight_) != 0) {
      output.writeDouble(1, maxWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (getAnimalPartsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(animalPartsMemoizedSerializedSize);
    }
    for (int i = 0; i < animalParts_.size(); i++) {
      output.writeInt64NoTag(animalParts_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(maxWeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, maxWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < animalParts_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(animalParts_.getLong(i));
      }
      size += dataSize;
      if (!getAnimalPartsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      animalPartsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.testrestapi.GetTrayResponse)) {
      return super.equals(obj);
    }
    com.example.testrestapi.GetTrayResponse other = (com.example.testrestapi.GetTrayResponse) obj;

    if (java.lang.Double.doubleToLongBits(getMaxWeight())
        != java.lang.Double.doubleToLongBits(
            other.getMaxWeight())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getAnimalPartsList()
        .equals(other.getAnimalPartsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAXWEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxWeight()));
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getAnimalPartsCount() > 0) {
      hash = (37 * hash) + ANIMALPARTS_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalPartsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.testrestapi.GetTrayResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.GetTrayResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.GetTrayResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.GetTrayResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.testrestapi.GetTrayResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.testrestapi.GetTrayResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.testrestapi.GetTrayResponse)
      com.example.testrestapi.GetTrayResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.testrestapi.SlaughterHouse.internal_static_com_example_testrestapi_GetTrayResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.testrestapi.SlaughterHouse.internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.testrestapi.GetTrayResponse.class, com.example.testrestapi.GetTrayResponse.Builder.class);
    }

    // Construct using com.example.testrestapi.GetTrayResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      maxWeight_ = 0D;

      description_ = "";

      animalParts_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.testrestapi.SlaughterHouse.internal_static_com_example_testrestapi_GetTrayResponse_descriptor;
    }

    @java.lang.Override
    public com.example.testrestapi.GetTrayResponse getDefaultInstanceForType() {
      return com.example.testrestapi.GetTrayResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.testrestapi.GetTrayResponse build() {
      com.example.testrestapi.GetTrayResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.testrestapi.GetTrayResponse buildPartial() {
      com.example.testrestapi.GetTrayResponse result = new com.example.testrestapi.GetTrayResponse(this);
      int from_bitField0_ = bitField0_;
      result.maxWeight_ = maxWeight_;
      result.description_ = description_;
      if (((bitField0_ & 0x00000001) != 0)) {
        animalParts_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.animalParts_ = animalParts_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.testrestapi.GetTrayResponse) {
        return mergeFrom((com.example.testrestapi.GetTrayResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.testrestapi.GetTrayResponse other) {
      if (other == com.example.testrestapi.GetTrayResponse.getDefaultInstance()) return this;
      if (other.getMaxWeight() != 0D) {
        setMaxWeight(other.getMaxWeight());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.animalParts_.isEmpty()) {
        if (animalParts_.isEmpty()) {
          animalParts_ = other.animalParts_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAnimalPartsIsMutable();
          animalParts_.addAll(other.animalParts_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.testrestapi.GetTrayResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.testrestapi.GetTrayResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private double maxWeight_ ;
    /**
     * <code>double maxWeight = 1;</code>
     * @return The maxWeight.
     */
    @java.lang.Override
    public double getMaxWeight() {
      return maxWeight_;
    }
    /**
     * <code>double maxWeight = 1;</code>
     * @param value The maxWeight to set.
     * @return This builder for chaining.
     */
    public Builder setMaxWeight(double value) {
      
      maxWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double maxWeight = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxWeight() {
      
      maxWeight_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList animalParts_ = emptyLongList();
    private void ensureAnimalPartsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animalParts_ = mutableCopy(animalParts_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @return A list containing the animalParts.
     */
    public java.util.List<java.lang.Long>
        getAnimalPartsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(animalParts_) : animalParts_;
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @return The count of animalParts.
     */
    public int getAnimalPartsCount() {
      return animalParts_.size();
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @param index The index of the element to return.
     * @return The animalParts at the given index.
     */
    public long getAnimalParts(int index) {
      return animalParts_.getLong(index);
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @param index The index to set the value at.
     * @param value The animalParts to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalParts(
        int index, long value) {
      ensureAnimalPartsIsMutable();
      animalParts_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @param value The animalParts to add.
     * @return This builder for chaining.
     */
    public Builder addAnimalParts(long value) {
      ensureAnimalPartsIsMutable();
      animalParts_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @param values The animalParts to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnimalParts(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAnimalPartsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, animalParts_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 animalParts = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalParts() {
      animalParts_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.testrestapi.GetTrayResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.testrestapi.GetTrayResponse)
  private static final com.example.testrestapi.GetTrayResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.testrestapi.GetTrayResponse();
  }

  public static com.example.testrestapi.GetTrayResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTrayResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTrayResponse>() {
    @java.lang.Override
    public GetTrayResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTrayResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTrayResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTrayResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.testrestapi.GetTrayResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

