// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public final class SlaughterHouse {
  private SlaughterHouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SlaughterHouse.proto\022\027com.example.test" +
      "restapi\"(\n\023GetAnimalIdsRequest\022\021\n\tproduc" +
      "tId\030\001 \001(\003\"-\n\024GetAnimalIdsResponse\022\025\n\tani" +
      "malIds\030\001 \003(\003B\002\020\001\"$\n\020GetAnimalRequest\022\020\n\010" +
      "animalId\030\001 \001(\003\"\203\001\n\021GetAnimalResponse\022\020\n\010" +
      "animalId\030\001 \001(\003\022\016\n\006weight\030\002 \001(\003\022\014\n\004isOk\030\003" +
      " \001(\010\022\016\n\006farmId\030\004 \001(\003\022\024\n\014animalTypeId\030\005 \001" +
      "(\003\022\030\n\020registrationDate\030\006 \001(\t\"s\n\023CreateAn" +
      "imalRequest\022\016\n\006weight\030\001 \001(\003\022\014\n\004isOk\030\002 \001(" +
      "\010\022\016\n\006farmId\030\003 \001(\003\022\024\n\014animalTypeId\030\004 \001(\003\022" +
      "\030\n\020registrationDate\030\005 \001(\t\",\n\024CreateAnima" +
      "lResponse\022\024\n\014confirmation\030\001 \001(\t\"\"\n\024GetAn" +
      "imalPartRequest\022\n\n\002id\030\001 \001(\003\"E\n\025GetAnimal" +
      "PartResponse\022\n\n\002id\030\001 \001(\003\022\016\n\006weight\030\002 \001(\001" +
      "\022\020\n\010animalId\030\003 \001(\003\";\n\027CreateAnimalPartRe" +
      "quest\022\016\n\006weight\030\001 \001(\003\022\020\n\010animalId\030\002 \001(\003\"" +
      "0\n\030CreateAnimalPartResponse\022\024\n\014confirmat" +
      "ion\030\001 \001(\t\"\"\n\024GetAnimalTypeRequest\022\n\n\002id\030" +
      "\001 \001(\003\"F\n\025GetAnimalTypeResponse\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"<\n" +
      "\027CreateAnimalTypeRequest\022\014\n\004name\030\001 \001(\t\022\023" +
      "\n\013description\030\002 \001(\t\"0\n\030CreateAnimalTypeR" +
      "esponse\022\024\n\014confirmation\030\001 \001(\t\"\034\n\016GetFarm" +
      "Request\022\n\n\002id\030\001 \001(\003\"R\n\017GetFarmResponse\022\n" +
      "\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001" +
      "(\t\022\023\n\013description\030\004 \001(\t\"H\n\021CreateFarmReq" +
      "uest\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\022\023\n\013" +
      "description\030\004 \001(\t\"*\n\022CreateFarmResponse\022" +
      "\024\n\014confirmation\030\001 \001(\t\"(\n\024GetProductIdsRe" +
      "quest\022\020\n\010animalId\030\001 \001(\003\"/\n\025GetProductIds" +
      "Response\022\026\n\nproductIds\030\001 \003(\003B\002\020\001\"\037\n\021GetP" +
      "roductRequest\022\n\n\002id\030\001 \001(\003\"L\n\022GetProductR" +
      "esponse\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001" +
      "(\t\022\023\n\013animalParts\030\003 \003(\003\"N\n\024CreateProduct" +
      "Request\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001" +
      "(\t\022\023\n\013animalParts\030\003 \003(\003\"-\n\025CreateProduct" +
      "Response\022\024\n\014confirmation\030\001 \001(\t\"\035\n\017GetSto" +
      "reRequest\022\n\n\002id\030\001 \001(\003\"[\n\020GetStoreRespons" +
      "e\022\014\n\004name\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\022\n\nproductIds\030\004 \003(\003\"]\n\022Cr" +
      "eateStoreRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010locati" +
      "on\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\022\n\nproduct" +
      "Ids\030\004 \003(\003\"+\n\023CreateStoreResponse\022\024\n\014conf" +
      "irmation\030\001 \001(\t\"\034\n\016GetTrayRequest\022\n\n\002id\030\001" +
      " \001(\003\"N\n\017GetTrayResponse\022\021\n\tmaxWeight\030\001 \001" +
      "(\001\022\023\n\013description\030\002 \001(\t\022\023\n\013animalParts\030\003" +
      " \003(\003\"P\n\021CreateTrayRequest\022\021\n\tmaxWeight\030\001" +
      " \001(\001\022\023\n\013description\030\002 \001(\t\022\023\n\013animalParts" +
      "\030\003 \003(\003\"*\n\022CreateTrayResponse\022\024\n\014confirma" +
      "tion\030\001 \001(\t\"&\n\030GetAnimalPartTypeRequest\022\n" +
      "\n\002id\030\001 \001(\003\"d\n\031GetAnimalPartTypeResponse\022" +
      "\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n\007tr" +
      "ayIds\030\003 \003(\003\022\023\n\013animalParts\030\004 \003(\003\"f\n\033Crea" +
      "teAnimalPartTypeRequest\022\014\n\004name\030\001 \001(\t\022\023\n" +
      "\013description\030\002 \001(\t\022\017\n\007trayIds\030\003 \003(\003\022\023\n\013a" +
      "nimalParts\030\004 \003(\003\"4\n\034CreateAnimalPartType" +
      "Response\022\024\n\014confirmation\030\001 \001(\t2\316\002\n\016Anima" +
      "lsService\022k\n\014getAnimalIds\022,.com.example." +
      "testrestapi.GetAnimalIdsRequest\032-.com.ex" +
      "ample.testrestapi.GetAnimalIdsResponse\022b" +
      "\n\tgetAnimal\022).com.example.testrestapi.Ge" +
      "tAnimalRequest\032*.com.example.testrestapi" +
      ".GetAnimalResponse\022k\n\014createAnimal\022,.com" +
      ".example.testrestapi.CreateAnimalRequest" +
      "\032-.com.example.testrestapi.CreateAnimalR" +
      "esponse2\375\001\n\022AnimalPartsService\022n\n\rgetAni" +
      "malPart\022-.com.example.testrestapi.GetAni" +
      "malPartRequest\032..com.example.testrestapi" +
      ".GetAnimalPartResponse\022w\n\020createAnimalPa" +
      "rt\0220.com.example.testrestapi.CreateAnima" +
      "lPartRequest\0321.com.example.testrestapi.C" +
      "reateAnimalPartResponse2\212\002\n\021AnimalTypeSe" +
      "rvice\022u\n\024getAnimalTypeService\022-.com.exam" +
      "ple.testrestapi.GetAnimalTypeRequest\032..c" +
      "om.example.testrestapi.GetAnimalTypeResp" +
      "onse\022~\n\027createAnimalTypeService\0220.com.ex" +
      "ample.testrestapi.CreateAnimalTypeReques" +
      "t\0321.com.example.testrestapi.CreateAnimal" +
      "TypeResponse2\340\001\n\013FarmService\022c\n\016getFarmS" +
      "ervice\022\'.com.example.testrestapi.GetFarm" +
      "Request\032(.com.example.testrestapi.GetFar" +
      "mResponse\022l\n\021createFarmService\022*.com.exa" +
      "mple.testrestapi.CreateFarmRequest\032+.com" +
      ".example.testrestapi.CreateFarmResponse2" +
      "\346\002\n\017ProductsService\022n\n\rgetProductIds\022-.c" +
      "om.example.testrestapi.GetProductIdsRequ" +
      "est\032..com.example.testrestapi.GetProduct" +
      "IdsResponse\022l\n\021getProductService\022*.com.e" +
      "xample.testrestapi.GetProductRequest\032+.c" +
      "om.example.testrestapi.GetProductRespons" +
      "e\022u\n\024createProductService\022-.com.example." +
      "testrestapi.CreateProductRequest\032..com.e" +
      "xample.testrestapi.CreateProductResponse" +
      "2\347\001\n\014StoreService\022f\n\017getStoreService\022(.c" +
      "om.example.testrestapi.GetStoreRequest\032)" +
      ".com.example.testrestapi.GetStoreRespons" +
      "e\022o\n\022createStoreService\022+.com.example.te" +
      "strestapi.CreateStoreRequest\032,.com.examp" +
      "le.testrestapi.CreateStoreResponse2\340\001\n\013T" +
      "rayService\022c\n\016getTrayService\022\'.com.examp" +
      "le.testrestapi.GetTrayRequest\032(.com.exam" +
      "ple.testrestapi.GetTrayResponse\022l\n\021creat" +
      "eTrayService\022*.com.example.testrestapi.C" +
      "reateTrayRequest\032+.com.example.testresta" +
      "pi.CreateTrayResponse2\250\002\n\025AnimalPartType" +
      "Service\022\201\001\n\030getAnimalPartTypeService\0221.c" +
      "om.example.testrestapi.GetAnimalPartType" +
      "Request\0322.com.example.testrestapi.GetAni" +
      "malPartTypeResponse\022\212\001\n\033createAnimalPart" +
      "TypeService\0224.com.example.testrestapi.Cr" +
      "eateAnimalPartTypeRequest\0325.com.example." +
      "testrestapi.CreateAnimalPartTypeResponse" +
      "B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor,
        new java.lang.String[] { "AnimalIds", });
    internal_static_com_example_testrestapi_GetAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_testrestapi_GetAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_GetAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_testrestapi_GetAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalResponse_descriptor,
        new java.lang.String[] { "AnimalId", "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_testrestapi_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_testrestapi_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_testrestapi_GetAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_testrestapi_GetAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor,
        new java.lang.String[] { "Id", "Weight", "AnimalId", });
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Weight", "AnimalId", });
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_example_testrestapi_GetFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetFarmRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_example_testrestapi_GetFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetFarmResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_CreateFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_example_testrestapi_CreateFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateFarmRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_CreateFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_example_testrestapi_CreateFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateFarmResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_example_testrestapi_GetProductIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_example_testrestapi_GetProductIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
    internal_static_com_example_testrestapi_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_example_testrestapi_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_example_testrestapi_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_example_testrestapi_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateProductRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_example_testrestapi_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateProductResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_example_testrestapi_GetStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetStoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_example_testrestapi_GetStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetStoreResponse_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_CreateStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_example_testrestapi_CreateStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateStoreRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_CreateStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_example_testrestapi_CreateStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateStoreResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_example_testrestapi_GetTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetTrayRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetTrayResponse_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_example_testrestapi_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateTrayRequest_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_example_testrestapi_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
