// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public final class SlaughterHouse {
  private SlaughterHouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SlaughterHouse.proto\022\027com.example.test" +
      "restapi\"(\n\023GetAnimalIdsRequest\022\021\n\tproduc" +
      "tId\030\001 \001(\003\"-\n\024GetAnimalIdsResponse\022\025\n\tani" +
      "malIds\030\001 \003(\003B\002\020\001\"$\n\020GetAnimalRequest\022\020\n\010" +
      "animalId\030\001 \001(\003\"\203\001\n\021GetAnimalResponse\022\020\n\010" +
      "animalId\030\001 \001(\003\022\016\n\006weight\030\002 \001(\001\022\014\n\004isOk\030\003" +
      " \001(\010\022\016\n\006farmId\030\004 \001(\003\022\024\n\014animalTypeId\030\005 \001" +
      "(\003\022\030\n\020registrationDate\030\006 \001(\t\"s\n\023CreateAn" +
      "imalRequest\022\016\n\006weight\030\001 \001(\001\022\014\n\004isOk\030\002 \001(" +
      "\010\022\016\n\006farmId\030\003 \001(\003\022\024\n\014animalTypeId\030\004 \001(\003\022" +
      "\030\n\020registrationDate\030\005 \001(\t\",\n\024CreateAnima" +
      "lResponse\022\024\n\014confirmation\030\001 \001(\t\"\"\n\024GetAn" +
      "imalPartRequest\022\n\n\002id\030\001 \001(\003\"E\n\025GetAnimal" +
      "PartResponse\022\n\n\002id\030\001 \001(\003\022\016\n\006weight\030\002 \001(\001" +
      "\022\020\n\010animalId\030\003 \001(\003\"c\n\027CreateAnimalPartRe" +
      "quest\022\016\n\006weight\030\001 \001(\003\022\020\n\010animalId\030\002 \001(\003\022" +
      "\016\n\006trayId\030\003 \001(\003\022\026\n\016animalPartType\030\004 \001(\003\"" +
      "0\n\030CreateAnimalPartResponse\022\024\n\014confirmat" +
      "ion\030\001 \001(\t\"\"\n\024GetAnimalTypeRequest\022\n\n\002id\030" +
      "\001 \001(\003\"F\n\025GetAnimalTypeResponse\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"<\n" +
      "\027CreateAnimalTypeRequest\022\014\n\004name\030\001 \001(\t\022\023" +
      "\n\013description\030\002 \001(\t\"0\n\030CreateAnimalTypeR" +
      "esponse\022\024\n\014confirmation\030\001 \001(\t\"\034\n\016GetFarm" +
      "Request\022\n\n\002id\030\001 \001(\003\"R\n\017GetFarmResponse\022\n" +
      "\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001" +
      "(\t\022\023\n\013description\030\004 \001(\t\"H\n\021CreateFarmReq" +
      "uest\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\022\023\n\013" +
      "description\030\004 \001(\t\"*\n\022CreateFarmResponse\022" +
      "\024\n\014confirmation\030\001 \001(\t\"(\n\024GetProductIdsRe" +
      "quest\022\020\n\010animalId\030\001 \001(\003\"/\n\025GetProductIds" +
      "Response\022\026\n\nproductIds\030\001 \003(\003B\002\020\001\"\037\n\021GetP" +
      "roductRequest\022\n\n\002id\030\001 \001(\003\"L\n\022GetProductR" +
      "esponse\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001" +
      "(\t\022\023\n\013animalParts\030\003 \003(\003\"9\n\024CreateProduct" +
      "Request\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001" +
      "(\t\"-\n\025CreateProductResponse\022\024\n\014confirmat" +
      "ion\030\001 \001(\t\"\035\n\017GetStoreRequest\022\n\n\002id\030\001 \001(\003" +
      "\"[\n\020GetStoreResponse\022\014\n\004name\030\001 \001(\t\022\020\n\010lo" +
      "cation\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\022\n\npro" +
      "ductIds\030\004 \003(\003\"]\n\022CreateStoreRequest\022\014\n\004n" +
      "ame\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\023\n\013descripti" +
      "on\030\003 \001(\t\022\022\n\nproductIds\030\004 \003(\003\"+\n\023CreateSt" +
      "oreResponse\022\024\n\014confirmation\030\001 \001(\t\"\034\n\016Get" +
      "TrayRequest\022\n\n\002id\030\001 \001(\003\"N\n\017GetTrayRespon" +
      "se\022\021\n\tmaxWeight\030\001 \001(\001\022\023\n\013description\030\002 \001" +
      "(\t\022\023\n\013animalParts\030\003 \003(\003\"P\n\021CreateTrayReq" +
      "uest\022\021\n\tmaxWeight\030\001 \001(\001\022\023\n\013description\030\002" +
      " \001(\t\022\023\n\013animalParts\030\003 \003(\003\"*\n\022CreateTrayR" +
      "esponse\022\024\n\014confirmation\030\001 \001(\t\"&\n\030GetAnim" +
      "alPartTypeRequest\022\n\n\002id\030\001 \001(\003\"d\n\031GetAnim" +
      "alPartTypeResponse\022\014\n\004name\030\001 \001(\t\022\023\n\013desc" +
      "ription\030\002 \001(\t\022\017\n\007trayIds\030\003 \003(\003\022\023\n\013animal" +
      "Parts\030\004 \003(\003\"f\n\033CreateAnimalPartTypeReque" +
      "st\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n" +
      "\007trayIds\030\003 \003(\003\022\023\n\013animalParts\030\004 \003(\003\"4\n\034C" +
      "reateAnimalPartTypeResponse\022\024\n\014confirmat" +
      "ion\030\001 \001(\t2\316\002\n\016AnimalsService\022k\n\014getAnima" +
      "lIds\022,.com.example.testrestapi.GetAnimal" +
      "IdsRequest\032-.com.example.testrestapi.Get" +
      "AnimalIdsResponse\022b\n\tgetAnimal\022).com.exa" +
      "mple.testrestapi.GetAnimalRequest\032*.com." +
      "example.testrestapi.GetAnimalResponse\022k\n" +
      "\014createAnimal\022,.com.example.testrestapi." +
      "CreateAnimalRequest\032-.com.example.testre" +
      "stapi.CreateAnimalResponse2\375\001\n\022AnimalPar" +
      "tsService\022n\n\rgetAnimalPart\022-.com.example" +
      ".testrestapi.GetAnimalPartRequest\032..com." +
      "example.testrestapi.GetAnimalPartRespons" +
      "e\022w\n\020createAnimalPart\0220.com.example.test" +
      "restapi.CreateAnimalPartRequest\0321.com.ex" +
      "ample.testrestapi.CreateAnimalPartRespon" +
      "se2\212\002\n\021AnimalTypeService\022u\n\024getAnimalTyp" +
      "eService\022-.com.example.testrestapi.GetAn" +
      "imalTypeRequest\032..com.example.testrestap" +
      "i.GetAnimalTypeResponse\022~\n\027createAnimalT" +
      "ypeService\0220.com.example.testrestapi.Cre" +
      "ateAnimalTypeRequest\0321.com.example.testr" +
      "estapi.CreateAnimalTypeResponse2\340\001\n\013Farm" +
      "Service\022c\n\016getFarmService\022\'.com.example." +
      "testrestapi.GetFarmRequest\032(.com.example" +
      ".testrestapi.GetFarmResponse\022l\n\021createFa" +
      "rmService\022*.com.example.testrestapi.Crea" +
      "teFarmRequest\032+.com.example.testrestapi." +
      "CreateFarmResponse2\346\002\n\017ProductsService\022n" +
      "\n\rgetProductIds\022-.com.example.testrestap" +
      "i.GetProductIdsRequest\032..com.example.tes" +
      "trestapi.GetProductIdsResponse\022l\n\021getPro" +
      "ductService\022*.com.example.testrestapi.Ge" +
      "tProductRequest\032+.com.example.testrestap" +
      "i.GetProductResponse\022u\n\024createProductSer" +
      "vice\022-.com.example.testrestapi.CreatePro" +
      "ductRequest\032..com.example.testrestapi.Cr" +
      "eateProductResponse2\347\001\n\014StoreService\022f\n\017" +
      "getStoreService\022(.com.example.testrestap" +
      "i.GetStoreRequest\032).com.example.testrest" +
      "api.GetStoreResponse\022o\n\022createStoreServi" +
      "ce\022+.com.example.testrestapi.CreateStore" +
      "Request\032,.com.example.testrestapi.Create" +
      "StoreResponse2\340\001\n\013TrayService\022c\n\016getTray" +
      "Service\022\'.com.example.testrestapi.GetTra" +
      "yRequest\032(.com.example.testrestapi.GetTr" +
      "ayResponse\022l\n\021createTrayService\022*.com.ex" +
      "ample.testrestapi.CreateTrayRequest\032+.co" +
      "m.example.testrestapi.CreateTrayResponse" +
      "2\250\002\n\025AnimalPartTypeService\022\201\001\n\030getAnimal" +
      "PartTypeService\0221.com.example.testrestap" +
      "i.GetAnimalPartTypeRequest\0322.com.example" +
      ".testrestapi.GetAnimalPartTypeResponse\022\212" +
      "\001\n\033createAnimalPartTypeService\0224.com.exa" +
      "mple.testrestapi.CreateAnimalPartTypeReq" +
      "uest\0325.com.example.testrestapi.CreateAni" +
      "malPartTypeResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_testrestapi_GetAnimalIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalIdsRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_testrestapi_GetAnimalIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalIdsResponse_descriptor,
        new java.lang.String[] { "AnimalIds", });
    internal_static_com_example_testrestapi_GetAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_testrestapi_GetAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_GetAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_testrestapi_GetAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalResponse_descriptor,
        new java.lang.String[] { "AnimalId", "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_testrestapi_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_testrestapi_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_testrestapi_GetAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_testrestapi_GetAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartResponse_descriptor,
        new java.lang.String[] { "Id", "Weight", "AnimalId", });
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_testrestapi_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Weight", "AnimalId", "TrayId", "AnimalPartType", });
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_testrestapi_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_testrestapi_GetAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_example_testrestapi_GetAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_example_testrestapi_CreateAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_example_testrestapi_CreateAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_example_testrestapi_GetFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetFarmRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_example_testrestapi_GetFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetFarmResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_CreateFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_example_testrestapi_CreateFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateFarmRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_CreateFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_example_testrestapi_CreateFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateFarmResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_example_testrestapi_GetProductIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductIdsRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_example_testrestapi_GetProductIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductIdsResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
    internal_static_com_example_testrestapi_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_example_testrestapi_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_example_testrestapi_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetProductResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_example_testrestapi_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateProductRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_example_testrestapi_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_example_testrestapi_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateProductResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_example_testrestapi_GetStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetStoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_example_testrestapi_GetStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetStoreResponse_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_CreateStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_example_testrestapi_CreateStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateStoreRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_CreateStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_example_testrestapi_CreateStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateStoreResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_example_testrestapi_GetTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetTrayRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_example_testrestapi_GetTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetTrayResponse_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_example_testrestapi_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateTrayRequest_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_example_testrestapi_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_GetAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_CreateAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
