// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi;

public interface UpdateAnimalPartProductIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.UpdateAnimalPartProductIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 productId = 2;</code>
   * @return The productId.
   */
  long getProductId();
}
