// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

public interface CreateAnimalPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.proto.CreateAnimalPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 weight = 1;</code>
   * @return The weight.
   */
  long getWeight();

  /**
   * <code>int64 animalId = 2;</code>
   * @return The animalId.
   */
  long getAnimalId();

  /**
   * <code>int64 trayId = 3;</code>
   * @return The trayId.
   */
  long getTrayId();

  /**
   * <code>int64 animalPartType = 4;</code>
   * @return The animalPartType.
   */
  long getAnimalPartType();
}
