// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

public interface GetAnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.proto.GetAnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 animalId = 1;</code>
   * @return The animalId.
   */
  long getAnimalId();
}
