// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

/**
 * Protobuf type {@code com.example.testrestapi.proto.GetAnimalResponse}
 */
public final class GetAnimalResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.testrestapi.proto.GetAnimalResponse)
    GetAnimalResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAnimalResponse.newBuilder() to construct.
  private GetAnimalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAnimalResponse() {
    registrationDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAnimalResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAnimalResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            animalId_ = input.readInt64();
            break;
          }
          case 16: {

            weight_ = input.readInt64();
            break;
          }
          case 24: {

            isOk_ = input.readBool();
            break;
          }
          case 32: {

            farmId_ = input.readInt64();
            break;
          }
          case 40: {

            animalTypeId_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            registrationDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetAnimalResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.testrestapi.proto.GetAnimalResponse.class, com.example.testrestapi.proto.GetAnimalResponse.Builder.class);
  }

  public static final int ANIMALID_FIELD_NUMBER = 1;
  private long animalId_;
  /**
   * <code>int64 animalId = 1;</code>
   * @return The animalId.
   */
  @java.lang.Override
  public long getAnimalId() {
    return animalId_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 2;
  private long weight_;
  /**
   * <code>int64 weight = 2;</code>
   * @return The weight.
   */
  @java.lang.Override
  public long getWeight() {
    return weight_;
  }

  public static final int ISOK_FIELD_NUMBER = 3;
  private boolean isOk_;
  /**
   * <code>bool isOk = 3;</code>
   * @return The isOk.
   */
  @java.lang.Override
  public boolean getIsOk() {
    return isOk_;
  }

  public static final int FARMID_FIELD_NUMBER = 4;
  private long farmId_;
  /**
   * <code>int64 farmId = 4;</code>
   * @return The farmId.
   */
  @java.lang.Override
  public long getFarmId() {
    return farmId_;
  }

  public static final int ANIMALTYPEID_FIELD_NUMBER = 5;
  private long animalTypeId_;
  /**
   * <code>int64 animalTypeId = 5;</code>
   * @return The animalTypeId.
   */
  @java.lang.Override
  public long getAnimalTypeId() {
    return animalTypeId_;
  }

  public static final int REGISTRATIONDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object registrationDate_;
  /**
   * <code>string registrationDate = 6;</code>
   * @return The registrationDate.
   */
  @java.lang.Override
  public java.lang.String getRegistrationDate() {
    java.lang.Object ref = registrationDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      registrationDate_ = s;
      return s;
    }
  }
  /**
   * <code>string registrationDate = 6;</code>
   * @return The bytes for registrationDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegistrationDateBytes() {
    java.lang.Object ref = registrationDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      registrationDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (animalId_ != 0L) {
      output.writeInt64(1, animalId_);
    }
    if (weight_ != 0L) {
      output.writeInt64(2, weight_);
    }
    if (isOk_ != false) {
      output.writeBool(3, isOk_);
    }
    if (farmId_ != 0L) {
      output.writeInt64(4, farmId_);
    }
    if (animalTypeId_ != 0L) {
      output.writeInt64(5, animalTypeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registrationDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, registrationDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (animalId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, animalId_);
    }
    if (weight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, weight_);
    }
    if (isOk_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isOk_);
    }
    if (farmId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, farmId_);
    }
    if (animalTypeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, animalTypeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registrationDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, registrationDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.testrestapi.proto.GetAnimalResponse)) {
      return super.equals(obj);
    }
    com.example.testrestapi.proto.GetAnimalResponse other = (com.example.testrestapi.proto.GetAnimalResponse) obj;

    if (getAnimalId()
        != other.getAnimalId()) return false;
    if (getWeight()
        != other.getWeight()) return false;
    if (getIsOk()
        != other.getIsOk()) return false;
    if (getFarmId()
        != other.getFarmId()) return false;
    if (getAnimalTypeId()
        != other.getAnimalTypeId()) return false;
    if (!getRegistrationDate()
        .equals(other.getRegistrationDate())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ANIMALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAnimalId());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWeight());
    hash = (37 * hash) + ISOK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOk());
    hash = (37 * hash) + FARMID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFarmId());
    hash = (37 * hash) + ANIMALTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAnimalTypeId());
    hash = (37 * hash) + REGISTRATIONDATE_FIELD_NUMBER;
    hash = (53 * hash) + getRegistrationDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.testrestapi.proto.GetAnimalResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.testrestapi.proto.GetAnimalResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.testrestapi.proto.GetAnimalResponse)
      com.example.testrestapi.proto.GetAnimalResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetAnimalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.testrestapi.proto.GetAnimalResponse.class, com.example.testrestapi.proto.GetAnimalResponse.Builder.class);
    }

    // Construct using com.example.testrestapi.proto.GetAnimalResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      animalId_ = 0L;

      weight_ = 0L;

      isOk_ = false;

      farmId_ = 0L;

      animalTypeId_ = 0L;

      registrationDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor;
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetAnimalResponse getDefaultInstanceForType() {
      return com.example.testrestapi.proto.GetAnimalResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetAnimalResponse build() {
      com.example.testrestapi.proto.GetAnimalResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetAnimalResponse buildPartial() {
      com.example.testrestapi.proto.GetAnimalResponse result = new com.example.testrestapi.proto.GetAnimalResponse(this);
      result.animalId_ = animalId_;
      result.weight_ = weight_;
      result.isOk_ = isOk_;
      result.farmId_ = farmId_;
      result.animalTypeId_ = animalTypeId_;
      result.registrationDate_ = registrationDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.testrestapi.proto.GetAnimalResponse) {
        return mergeFrom((com.example.testrestapi.proto.GetAnimalResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.testrestapi.proto.GetAnimalResponse other) {
      if (other == com.example.testrestapi.proto.GetAnimalResponse.getDefaultInstance()) return this;
      if (other.getAnimalId() != 0L) {
        setAnimalId(other.getAnimalId());
      }
      if (other.getWeight() != 0L) {
        setWeight(other.getWeight());
      }
      if (other.getIsOk() != false) {
        setIsOk(other.getIsOk());
      }
      if (other.getFarmId() != 0L) {
        setFarmId(other.getFarmId());
      }
      if (other.getAnimalTypeId() != 0L) {
        setAnimalTypeId(other.getAnimalTypeId());
      }
      if (!other.getRegistrationDate().isEmpty()) {
        registrationDate_ = other.registrationDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.testrestapi.proto.GetAnimalResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.testrestapi.proto.GetAnimalResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long animalId_ ;
    /**
     * <code>int64 animalId = 1;</code>
     * @return The animalId.
     */
    @java.lang.Override
    public long getAnimalId() {
      return animalId_;
    }
    /**
     * <code>int64 animalId = 1;</code>
     * @param value The animalId to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalId(long value) {
      
      animalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 animalId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalId() {
      
      animalId_ = 0L;
      onChanged();
      return this;
    }

    private long weight_ ;
    /**
     * <code>int64 weight = 2;</code>
     * @return The weight.
     */
    @java.lang.Override
    public long getWeight() {
      return weight_;
    }
    /**
     * <code>int64 weight = 2;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(long value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 weight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0L;
      onChanged();
      return this;
    }

    private boolean isOk_ ;
    /**
     * <code>bool isOk = 3;</code>
     * @return The isOk.
     */
    @java.lang.Override
    public boolean getIsOk() {
      return isOk_;
    }
    /**
     * <code>bool isOk = 3;</code>
     * @param value The isOk to set.
     * @return This builder for chaining.
     */
    public Builder setIsOk(boolean value) {
      
      isOk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOk = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOk() {
      
      isOk_ = false;
      onChanged();
      return this;
    }

    private long farmId_ ;
    /**
     * <code>int64 farmId = 4;</code>
     * @return The farmId.
     */
    @java.lang.Override
    public long getFarmId() {
      return farmId_;
    }
    /**
     * <code>int64 farmId = 4;</code>
     * @param value The farmId to set.
     * @return This builder for chaining.
     */
    public Builder setFarmId(long value) {
      
      farmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 farmId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFarmId() {
      
      farmId_ = 0L;
      onChanged();
      return this;
    }

    private long animalTypeId_ ;
    /**
     * <code>int64 animalTypeId = 5;</code>
     * @return The animalTypeId.
     */
    @java.lang.Override
    public long getAnimalTypeId() {
      return animalTypeId_;
    }
    /**
     * <code>int64 animalTypeId = 5;</code>
     * @param value The animalTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalTypeId(long value) {
      
      animalTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 animalTypeId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalTypeId() {
      
      animalTypeId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object registrationDate_ = "";
    /**
     * <code>string registrationDate = 6;</code>
     * @return The registrationDate.
     */
    public java.lang.String getRegistrationDate() {
      java.lang.Object ref = registrationDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registrationDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string registrationDate = 6;</code>
     * @return The bytes for registrationDate.
     */
    public com.google.protobuf.ByteString
        getRegistrationDateBytes() {
      java.lang.Object ref = registrationDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registrationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string registrationDate = 6;</code>
     * @param value The registrationDate to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      registrationDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string registrationDate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationDate() {
      
      registrationDate_ = getDefaultInstance().getRegistrationDate();
      onChanged();
      return this;
    }
    /**
     * <code>string registrationDate = 6;</code>
     * @param value The bytes for registrationDate to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      registrationDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.testrestapi.proto.GetAnimalResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.testrestapi.proto.GetAnimalResponse)
  private static final com.example.testrestapi.proto.GetAnimalResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.testrestapi.proto.GetAnimalResponse();
  }

  public static com.example.testrestapi.proto.GetAnimalResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAnimalResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAnimalResponse>() {
    @java.lang.Override
    public GetAnimalResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAnimalResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAnimalResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAnimalResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.testrestapi.proto.GetAnimalResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

