// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

public interface GetAnimalPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.testrestapi.proto.GetAnimalPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>double weight = 2;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int64 animalId = 3;</code>
   * @return The animalId.
   */
  long getAnimalId();
}
