// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

/**
 * Protobuf type {@code com.example.testrestapi.proto.GetProductIdsResponse}
 */
public final class GetProductIdsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.testrestapi.proto.GetProductIdsResponse)
    GetProductIdsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProductIdsResponse.newBuilder() to construct.
  private GetProductIdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProductIdsResponse() {
    productIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProductIdsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetProductIdsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              productIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            productIds_.addLong(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              productIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              productIds_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        productIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetProductIdsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.testrestapi.proto.GetProductIdsResponse.class, com.example.testrestapi.proto.GetProductIdsResponse.Builder.class);
  }

  public static final int PRODUCTIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList productIds_;
  /**
   * <code>repeated int64 productIds = 1 [packed = true];</code>
   * @return A list containing the productIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getProductIdsList() {
    return productIds_;
  }
  /**
   * <code>repeated int64 productIds = 1 [packed = true];</code>
   * @return The count of productIds.
   */
  public int getProductIdsCount() {
    return productIds_.size();
  }
  /**
   * <code>repeated int64 productIds = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  public long getProductIds(int index) {
    return productIds_.getLong(index);
  }
  private int productIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getProductIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(productIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < productIds_.size(); i++) {
      output.writeInt64NoTag(productIds_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < productIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(productIds_.getLong(i));
      }
      size += dataSize;
      if (!getProductIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      productIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.testrestapi.proto.GetProductIdsResponse)) {
      return super.equals(obj);
    }
    com.example.testrestapi.proto.GetProductIdsResponse other = (com.example.testrestapi.proto.GetProductIdsResponse) obj;

    if (!getProductIdsList()
        .equals(other.getProductIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductIdsCount() > 0) {
      hash = (37 * hash) + PRODUCTIDS_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.testrestapi.proto.GetProductIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.testrestapi.proto.GetProductIdsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.testrestapi.proto.GetProductIdsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.testrestapi.proto.GetProductIdsResponse)
      com.example.testrestapi.proto.GetProductIdsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetProductIdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.testrestapi.proto.GetProductIdsResponse.class, com.example.testrestapi.proto.GetProductIdsResponse.Builder.class);
    }

    // Construct using com.example.testrestapi.proto.GetProductIdsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.testrestapi.proto.SlaughterHouse.internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetProductIdsResponse getDefaultInstanceForType() {
      return com.example.testrestapi.proto.GetProductIdsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetProductIdsResponse build() {
      com.example.testrestapi.proto.GetProductIdsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.testrestapi.proto.GetProductIdsResponse buildPartial() {
      com.example.testrestapi.proto.GetProductIdsResponse result = new com.example.testrestapi.proto.GetProductIdsResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        productIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productIds_ = productIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.testrestapi.proto.GetProductIdsResponse) {
        return mergeFrom((com.example.testrestapi.proto.GetProductIdsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.testrestapi.proto.GetProductIdsResponse other) {
      if (other == com.example.testrestapi.proto.GetProductIdsResponse.getDefaultInstance()) return this;
      if (!other.productIds_.isEmpty()) {
        if (productIds_.isEmpty()) {
          productIds_ = other.productIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductIdsIsMutable();
          productIds_.addAll(other.productIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.testrestapi.proto.GetProductIdsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.testrestapi.proto.GetProductIdsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList productIds_ = emptyLongList();
    private void ensureProductIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productIds_ = mutableCopy(productIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @return A list containing the productIds.
     */
    public java.util.List<java.lang.Long>
        getProductIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(productIds_) : productIds_;
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public long getProductIds(int index) {
      return productIds_.getLong(index);
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The productIds to set.
     * @return This builder for chaining.
     */
    public Builder setProductIds(
        int index, long value) {
      ensureProductIdsIsMutable();
      productIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @param value The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addProductIds(long value) {
      ensureProductIdsIsMutable();
      productIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @param values The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureProductIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 productIds = 1 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearProductIds() {
      productIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.testrestapi.proto.GetProductIdsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.testrestapi.proto.GetProductIdsResponse)
  private static final com.example.testrestapi.proto.GetProductIdsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.testrestapi.proto.GetProductIdsResponse();
  }

  public static com.example.testrestapi.proto.GetProductIdsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProductIdsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetProductIdsResponse>() {
    @java.lang.Override
    public GetProductIdsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetProductIdsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetProductIdsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProductIdsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.testrestapi.proto.GetProductIdsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

