// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package com.example.testrestapi.proto;

public final class SlaughterHouse {
  private SlaughterHouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetProductIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetProductIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetProductIdsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_GetAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SlaughterHouse.proto\022\035com.example.test" +
      "restapi.proto\"(\n\023GetAnimalIdsRequest\022\021\n\t" +
      "productId\030\001 \001(\003\"-\n\024GetAnimalIdsResponse\022" +
      "\025\n\tanimalIds\030\001 \003(\003B\002\020\001\"$\n\020GetAnimalReque" +
      "st\022\020\n\010animalId\030\001 \001(\003\"\203\001\n\021GetAnimalRespon" +
      "se\022\020\n\010animalId\030\001 \001(\003\022\016\n\006weight\030\002 \001(\003\022\014\n\004" +
      "isOk\030\003 \001(\010\022\016\n\006farmId\030\004 \001(\003\022\024\n\014animalType" +
      "Id\030\005 \001(\003\022\030\n\020registrationDate\030\006 \001(\t\"s\n\023Cr" +
      "eateAnimalRequest\022\016\n\006weight\030\001 \001(\001\022\014\n\004isO" +
      "k\030\002 \001(\010\022\016\n\006farmId\030\003 \001(\003\022\024\n\014animalTypeId\030" +
      "\004 \001(\003\022\030\n\020registrationDate\030\005 \001(\t\",\n\024Creat" +
      "eAnimalResponse\022\024\n\014confirmation\030\001 \001(\t\"\"\n" +
      "\024GetAnimalPartRequest\022\n\n\002id\030\001 \001(\003\"E\n\025Get" +
      "AnimalPartResponse\022\n\n\002id\030\001 \001(\003\022\016\n\006weight" +
      "\030\002 \001(\001\022\020\n\010animalId\030\003 \001(\003\"c\n\027CreateAnimal" +
      "PartRequest\022\016\n\006weight\030\001 \001(\003\022\020\n\010animalId\030" +
      "\002 \001(\003\022\016\n\006trayId\030\003 \001(\003\022\026\n\016animalPartType\030" +
      "\004 \001(\003\"0\n\030CreateAnimalPartResponse\022\024\n\014con" +
      "firmation\030\001 \001(\t\"\"\n\024GetAnimalTypeRequest\022" +
      "\n\n\002id\030\001 \001(\003\"F\n\025GetAnimalTypeResponse\022\n\n\002" +
      "id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 " +
      "\001(\t\"<\n\027CreateAnimalTypeRequest\022\014\n\004name\030\001" +
      " \001(\t\022\023\n\013description\030\002 \001(\t\"0\n\030CreateAnima" +
      "lTypeResponse\022\024\n\014confirmation\030\001 \001(\t\"\034\n\016G" +
      "etFarmRequest\022\n\n\002id\030\001 \001(\003\"R\n\017GetFarmResp" +
      "onse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010locati" +
      "on\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"H\n\021CreateF" +
      "armRequest\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001" +
      "(\t\022\023\n\013description\030\004 \001(\t\"*\n\022CreateFarmRes" +
      "ponse\022\024\n\014confirmation\030\001 \001(\t\"(\n\024GetProduc" +
      "tIdsRequest\022\020\n\010animalId\030\001 \001(\003\"/\n\025GetProd" +
      "uctIdsResponse\022\026\n\nproductIds\030\001 \003(\003B\002\020\001\"\037" +
      "\n\021GetProductRequest\022\n\n\002id\030\001 \001(\003\"L\n\022GetPr" +
      "oductResponse\022\014\n\004name\030\001 \001(\t\022\023\n\013descripti" +
      "on\030\002 \001(\t\022\023\n\013animalParts\030\003 \003(\003\"9\n\024CreateP" +
      "roductRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013descripti" +
      "on\030\002 \001(\t\"#\n\025CreateProductResponse\022\n\n\002id\030" +
      "\001 \001(\003\"\035\n\017GetStoreRequest\022\n\n\002id\030\001 \001(\003\"[\n\020" +
      "GetStoreResponse\022\014\n\004name\030\001 \001(\t\022\020\n\010locati" +
      "on\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\022\n\nproduct" +
      "Ids\030\004 \003(\003\"]\n\022CreateStoreRequest\022\014\n\004name\030" +
      "\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\023\n\013description\030\003" +
      " \001(\t\022\022\n\nproductIds\030\004 \003(\003\"+\n\023CreateStoreR" +
      "esponse\022\024\n\014confirmation\030\001 \001(\t\"\034\n\016GetTray" +
      "Request\022\n\n\002id\030\001 \001(\003\"N\n\017GetTrayResponse\022\021" +
      "\n\tmaxWeight\030\001 \001(\001\022\023\n\013description\030\002 \001(\t\022\023" +
      "\n\013animalParts\030\003 \003(\003\"P\n\021CreateTrayRequest" +
      "\022\021\n\tmaxWeight\030\001 \001(\001\022\023\n\013description\030\002 \001(\t" +
      "\022\023\n\013animalParts\030\003 \003(\003\"*\n\022CreateTrayRespo" +
      "nse\022\024\n\014confirmation\030\001 \001(\t\"&\n\030GetAnimalPa" +
      "rtTypeRequest\022\n\n\002id\030\001 \001(\003\"d\n\031GetAnimalPa" +
      "rtTypeResponse\022\014\n\004name\030\001 \001(\t\022\023\n\013descript" +
      "ion\030\002 \001(\t\022\017\n\007trayIds\030\003 \003(\003\022\023\n\013animalPart" +
      "s\030\004 \003(\003\"f\n\033CreateAnimalPartTypeRequest\022\014" +
      "\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n\007tra" +
      "yIds\030\003 \003(\003\022\023\n\013animalParts\030\004 \003(\003\"4\n\034Creat" +
      "eAnimalPartTypeResponse\022\024\n\014confirmation\030" +
      "\001 \001(\t\"A\n UpdateAnimalPartProductIdReques" +
      "t\022\n\n\002id\030\001 \001(\003\022\021\n\tproductId\030\002 \001(\003\"9\n!Upda" +
      "teAnimalPartProductIdResponse\022\024\n\014confirm" +
      "ation\030\001 \001(\t2\362\002\n\016AnimalsService\022w\n\014getAni" +
      "malIds\0222.com.example.testrestapi.proto.G" +
      "etAnimalIdsRequest\0323.com.example.testres" +
      "tapi.proto.GetAnimalIdsResponse\022n\n\tgetAn" +
      "imal\022/.com.example.testrestapi.proto.Get" +
      "AnimalRequest\0320.com.example.testrestapi." +
      "proto.GetAnimalResponse\022w\n\014createAnimal\022" +
      "2.com.example.testrestapi.proto.CreateAn" +
      "imalRequest\0323.com.example.testrestapi.pr" +
      "oto.CreateAnimalResponse2\267\003\n\022AnimalParts" +
      "Service\022z\n\rgetAnimalPart\0223.com.example.t" +
      "estrestapi.proto.GetAnimalPartRequest\0324." +
      "com.example.testrestapi.proto.GetAnimalP" +
      "artResponse\022\203\001\n\020createAnimalPart\0226.com.e" +
      "xample.testrestapi.proto.CreateAnimalPar" +
      "tRequest\0327.com.example.testrestapi.proto" +
      ".CreateAnimalPartResponse\022\236\001\n\031updateAnim" +
      "alPartProductId\022?.com.example.testrestap" +
      "i.proto.UpdateAnimalPartProductIdRequest" +
      "\032@.com.example.testrestapi.proto.UpdateA" +
      "nimalPartProductIdResponse2\244\002\n\021AnimalTyp" +
      "eService\022\201\001\n\024getAnimalTypeService\0223.com." +
      "example.testrestapi.proto.GetAnimalTypeR" +
      "equest\0324.com.example.testrestapi.proto.G" +
      "etAnimalTypeResponse\022\212\001\n\027createAnimalTyp" +
      "eService\0226.com.example.testrestapi.proto" +
      ".CreateAnimalTypeRequest\0327.com.example.t" +
      "estrestapi.proto.CreateAnimalTypeRespons" +
      "e2\370\001\n\013FarmService\022o\n\016getFarmService\022-.co" +
      "m.example.testrestapi.proto.GetFarmReque" +
      "st\032..com.example.testrestapi.proto.GetFa" +
      "rmResponse\022x\n\021createFarmService\0220.com.ex" +
      "ample.testrestapi.proto.CreateFarmReques" +
      "t\0321.com.example.testrestapi.proto.Create" +
      "FarmResponse2\213\003\n\017ProductsService\022z\n\rgetP" +
      "roductIds\0223.com.example.testrestapi.prot" +
      "o.GetProductIdsRequest\0324.com.example.tes" +
      "trestapi.proto.GetProductIdsResponse\022x\n\021" +
      "getProductService\0220.com.example.testrest" +
      "api.proto.GetProductRequest\0321.com.exampl" +
      "e.testrestapi.proto.GetProductResponse\022\201" +
      "\001\n\024createProductService\0223.com.example.te" +
      "strestapi.proto.CreateProductRequest\0324.c" +
      "om.example.testrestapi.proto.CreateProdu" +
      "ctResponse2\377\001\n\014StoreService\022r\n\017getStoreS" +
      "ervice\022..com.example.testrestapi.proto.G" +
      "etStoreRequest\032/.com.example.testrestapi" +
      ".proto.GetStoreResponse\022{\n\022createStoreSe" +
      "rvice\0221.com.example.testrestapi.proto.Cr" +
      "eateStoreRequest\0322.com.example.testresta" +
      "pi.proto.CreateStoreResponse2\370\001\n\013TraySer" +
      "vice\022o\n\016getTrayService\022-.com.example.tes" +
      "trestapi.proto.GetTrayRequest\032..com.exam" +
      "ple.testrestapi.proto.GetTrayResponse\022x\n" +
      "\021createTrayService\0220.com.example.testres" +
      "tapi.proto.CreateTrayRequest\0321.com.examp" +
      "le.testrestapi.proto.CreateTrayResponse2" +
      "\300\002\n\025AnimalPartTypeService\022\215\001\n\030getAnimalP" +
      "artTypeService\0227.com.example.testrestapi" +
      ".proto.GetAnimalPartTypeRequest\0328.com.ex" +
      "ample.testrestapi.proto.GetAnimalPartTyp" +
      "eResponse\022\226\001\n\033createAnimalPartTypeServic" +
      "e\022:.com.example.testrestapi.proto.Create" +
      "AnimalPartTypeRequest\032;.com.example.test" +
      "restapi.proto.CreateAnimalPartTypeRespon" +
      "seB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_testrestapi_proto_GetAnimalIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_testrestapi_proto_GetAnimalIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalIdsRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_example_testrestapi_proto_GetAnimalIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_testrestapi_proto_GetAnimalIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalIdsResponse_descriptor,
        new java.lang.String[] { "AnimalIds", });
    internal_static_com_example_testrestapi_proto_GetAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_testrestapi_proto_GetAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_testrestapi_proto_GetAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalResponse_descriptor,
        new java.lang.String[] { "AnimalId", "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_proto_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_testrestapi_proto_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "Weight", "IsOk", "FarmId", "AnimalTypeId", "RegistrationDate", });
    internal_static_com_example_testrestapi_proto_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_testrestapi_proto_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_testrestapi_proto_GetAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalPartRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_testrestapi_proto_GetAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalPartResponse_descriptor,
        new java.lang.String[] { "Id", "Weight", "AnimalId", });
    internal_static_com_example_testrestapi_proto_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_testrestapi_proto_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Weight", "AnimalId", "TrayId", "AnimalPartType", });
    internal_static_com_example_testrestapi_proto_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_testrestapi_proto_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_testrestapi_proto_GetAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_example_testrestapi_proto_GetAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_example_testrestapi_proto_CreateAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_example_testrestapi_proto_GetFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetFarmRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_example_testrestapi_proto_GetFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetFarmResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_proto_CreateFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_example_testrestapi_proto_CreateFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateFarmRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", });
    internal_static_com_example_testrestapi_proto_CreateFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_example_testrestapi_proto_CreateFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateFarmResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetProductIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_example_testrestapi_proto_GetProductIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetProductIdsRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_example_testrestapi_proto_GetProductIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetProductIdsResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
    internal_static_com_example_testrestapi_proto_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_example_testrestapi_proto_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_example_testrestapi_proto_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetProductResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_proto_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_example_testrestapi_proto_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateProductRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_example_testrestapi_proto_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_example_testrestapi_proto_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateProductResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_example_testrestapi_proto_GetStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetStoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_example_testrestapi_proto_GetStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetStoreResponse_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_proto_CreateStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_example_testrestapi_proto_CreateStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateStoreRequest_descriptor,
        new java.lang.String[] { "Name", "Location", "Description", "ProductIds", });
    internal_static_com_example_testrestapi_proto_CreateStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_example_testrestapi_proto_CreateStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateStoreResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_example_testrestapi_proto_GetTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetTrayRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_example_testrestapi_proto_GetTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetTrayResponse_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_proto_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_example_testrestapi_proto_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateTrayRequest_descriptor,
        new java.lang.String[] { "MaxWeight", "Description", "AnimalParts", });
    internal_static_com_example_testrestapi_proto_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_example_testrestapi_proto_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_example_testrestapi_proto_GetAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_GetAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayIds", "AnimalParts", });
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_CreateAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdRequest_descriptor,
        new java.lang.String[] { "Id", "ProductId", });
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_testrestapi_proto_UpdateAnimalPartProductIdResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
